import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Policy() {
  return (
    <div>
      <Header />
      <br />
      <br />
      <div id="ter">
        <h1 className="center">PRIVACY POLICY</h1>
        <br /><br />
        <p>
          At Blogermen, we value your privacy and are committed to protecting
          your personal information. This Privacy Policy outlines how we
          collect, use, and safeguard your data when you visit our website at
          www.blogermen.com. By using our Website, you consent to
          the practices described herein.
        </p><br />
        <h2>1. Information We Collect</h2>
        <p>We may collect the following types of information:</p>
        Personal Information: This includes information you provide voluntarily,
        such as your name and email address when you subscribe or contact us.
        Usage Data: We automatically collect information about your interaction
        with our Website, including your IP address, browser type, and pages
        visited. Cookies: We use cookies and similar technologies to enhance
        your experience. You can manage cookie preferences through your browser.
        <br /> <br />
        <h2>2. How We Use Your Information</h2>
        <p>We use your information for the following purposes:</p>
        To Provide Services: Delivering content and responding to inquiries. To
        Improve Our Website: Analyzing usage to enhance user experience. To
        Communicate: Sending updates and marketing communications with your
        consent. <br /> <br />
        <h2>3. Data Security</h2>
        <p>
          We implement reasonable security measures to protect your information.
          However, no method of transmission over the internet is 100% secure.
        </p> <br />
        <h2>4. Third-Party Links</h2>
        <p>
          Our Website may contain links to third-party sites. We are not
          responsible for their content or privacy practices.
        </p> <br />
        <h2>5. Changes to This Privacy Policy</h2>
        <p>
          We may update this policy from time to time. We will notify you of any
          significant changes by posting a notice on our Website.
        </p> <br />
        <h2>6. Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact us
          at contact@blogermen.com.
        </p> <br />
        <p>Most text has been generated by the help of Chatgpt.</p>
        <br />
        <p>Thank you for visiting Blogermen!</p>
      </div>
      <br />
      <br />
      <Footer />
    </div>
  );
}
